name: degiro_api
description: Unofficial Degiro APIs. A Dart wrapper to use the Degiro APIs in a simple way.
version: 0.3.0
homepage: https://github.com/marcoredz/degiro_api
repository: https://github.com/marcoredz/degiro_api

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  dio: ^4.0.4
  multiple_result: ^1.0.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
