name: degiro_api
description: Unofficial Degiro APIs. A Dart wrapper to use the Degiro APIs in a simple way.
version: 0.4.0
repository: https://github.com/marcoredz/degiro_api

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  dio: ^4.0.4
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  multiple_result: ^1.0.4

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.5.0
  lints: ^1.0.1
  test: ^1.16.0
