name: degiro_api
description: Unofficial Degiro APIs. A Dart wrapper to use the Degiro APIs in a simple way.
version: 0.6.3
repository: https://github.com/marcoredz/degiro_api

environment:
  sdk: '>=2.17.5 <4.0.0'

dependencies:
  dio: ^5.3.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  multiple_result: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.9
